language: go

go:
  - "1.10.3"

services:
  - docker

env:
  global:
    - REPO=quay.io/wantedly/rigger
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e 's/[^a-zA-Z0-9]/_/g')
    - TAG=$BRANCH-${TRAVIS_COMMIT::8}
    - secure: "Hefuw68bjVaT6m5f/GTZtGxCUvXOBQPSvXzt7wmUvLkT1bivMYcAVYRMVXe6RK6j0bUBpArD8C5PkTCNPF5oKLVwuiEABhskyuwAgp5KO59vhI8KKg7J0S6OKo2A9FWxdhyjzN4LwoQj6JwScxs6eqJI3U79a1SIoTZ08X3he0elZupn5TO58fxqTXetjjj7v+SaPTMxDha2z2X3o5g4qP9qlDBQCja2jHB3s/5CLM1d6agWTxzt7TMQbeZUHGutYjQnlucDLn6E4xUZXVZcNju6izBj4FHfydmCixOdFUCxp13y14ccR5H+oKvZSGUk0tgISaMkCOPqUZfktXJxBNXEyVVJVUsaWBH7kR0IWtUtzah4AlUdzGGhE5Go2YqyR46dV0MW71+e+WujtnRgJUAEwGXghbqfwHoElag+HcIq535wyRr18206w2ZeV4BkzJpwdZAkFQa5B/TuPva4Z+I2dy3mLSSsDwF+IRSgo8oTUtrcmwDNr/gx3QIahI3A8hQYIvtr6NORzuQUqKvcsqVDsf8uLqSGdVd5iuycoCMYsZ1iGmx+5PoJ5FkUFfzXBlOun3LxBxERQh57QXofH56nIqMYhrv11yVseLswvq0ZeF8t2LcRFEVVrvtJvUKpptg14r3Bt7+LdoWhQRUVf2Rl0CnCzcmO0nK6Fmd0xZo="
    - secure: "bO+cO2rz+A6lIaPC3Wwd22gtQORbrOxtWN8SUDaa/4LMKN7/V5cqtlmMWCLNIe+Uti3jYcvBRNo3xSNhYvvVCua6wWZhPlUERzt52dHcGQ7zXCAEs2nYLEKEI1ktygfRPtxV9lBv6rCwWOy41QKgFPtl8vSd4VIWBdLs5k2u2Z2r8RFhtnRixunVsbfRQ419WIGzlNopKtYvCh8eooKTeOT7XjIZBMSegWd3+MWWldH578hAm9Vkp/nw7Q9OHi7jQDIZ3hhgSysr+CfjjIe/fLp/O+46Rjanj9vulRqZ02nIo9sNAqyiG9JyHbLrkH4qAZASYsenp2ijIUJQuVgAwVu8XreZECtHRn+LJ2kavtMMkYt8k5SXBnE9s2Mki1s+0AJIXZlGwaQPUp+ElCltJw8B9DYTrHhq+MsKgiT+DKbaIi5bYql9bNmbFUA6sK5J8MHUewXGJcs68EoVPi05m0+HbDemzWibR0c3tkX4WERsmaw2tkcarMAhYMstljI7uYyfoLsY7c1Y6jKwRFo0VmYgI+yhADW//jjypoLx71PHiM8x+ULXSItpIeubNauZiJmzblcT5Uj17JGK/X+cZqLLbngYWBNVVUQLOYIi8wfc01JJp+j9HJ9PawnemLhCoaLdGzkPOEYnl8qhe3W4t2nCxKgmBH6PhKXjFx7Ka8A="

cache:
  directories:
    - vendor
    - $GOPATH/pkg/dep

before_install:
  - go get -u -v github.com/golang/dep/cmd/dep

install:
  - dep ensure -v
  - scripts/install_kubebuilder

script:
  - make test
  - scripts/ci-build

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/ci-deploy
  on:
    branch: master
