#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

os=$(go env GOOS)
arch=$(go env GOARCH)

# from. https://book.kubebuilder.io/quick-start.html#installation

# download kubebuilder and extract it to tmp
curl -sL https://go.kubebuilder.io/dl/2.0.0-alpha.4/${os}/${arch} | tar -xz -C /tmp/

# move to a long-term location and put it on your path
# (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
sudo mv /tmp/kubebuilder_2.0.0-alpha.4_${os}_${arch} /usr/local/kubebuilder
export PATH=$PATH:/usr/local/kubebuilder/bin

